services:
  website:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: "9000"
      HOST: "0.0.0.0"
      VIRTUAL_HOST: chrismangan.net
    ports:
      - "9000:9000"
    network_mode: bridge
