services:
  website:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: "8001"
      HOST: "localhost"
      VIRTUAL_HOST: chrismangan.net
    ports:
      - "8001:8001"
