name: Deploy to server

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: self-hosted
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: Deploy
      run: docker compose up --build -d
    env:
      hello: "hi"
